[Unit]
Description=Flask App Service
After=network.target

[Service]
User=ec2-user
WorkingDirectory=/home/ec2-user/cicd
ExecStart=/usr/bin/python3 /home/ec2-user/cicd/app.py
Restart=always

[Install]
WantedBy=multi-user.target